// src/services/initial-data.ts
import type { Tarea } from '../types/tarea.interface';

export const tareasIniciales: Tarea[] = [
  {
    id: 1,
    titulo: 'Desarrollo de Interfaz Base',
    descripcion: 'Diseñar los componentes visuales iniciales de la aplicación móvil utilizando layouts responsivos.',
    asignatura: 'Programación Móvil',
    fecha_entrega: '2026-06-02',
    prioridad: 'alta',
    estado: 'en proceso',
    activo: true,
  },
  {
    id: 2,
    titulo: 'Análisis de Vulnerabilidades en Servidores',
    descripcion: 'Ejecutar pruebas de penetración iniciales y escanear puertos abiertos en entornos Linux virtuales.',
    asignatura: 'Seguridad de Redes',
    fecha_entrega: '2026-06-05',
    prioridad: 'alta',
    estado: 'pendiente',
    activo: true,
  },
  {
    id: 3,
    titulo: 'Configuración de Servidor DHCP local',
    descripcion: 'Implementar el direccionamiento estático y el pool de IPs dinámicas en Windows Server 2025.',
    asignatura: 'Sistemas Operativos III',
    fecha_entrega: '2026-05-28',
    prioridad: 'media',
    estado: 'finalizada',
    activo: true,
  },
  {
    id: 4,
    titulo: 'Diseño de Modelo de Datos Clave-Valor',
    descripcion: 'Estructurar las colecciones base y colecciones documentales para la persistencia del inventario en Redis.',
    asignatura: 'Bases de Datos No Relacionales',
    fecha_entrega: '2026-06-08',
    prioridad: 'media',
    estado: 'pendiente',
    activo: true,
  },
  {
    id: 5,
    titulo: 'Resolución de Integrales Múltiples',
    descripcion: 'Resolver la guía práctica de ejercicios sobre integrales dobles y aplicaciones de áreas de superficies.',
    asignatura: 'Análisis Matemático',
    fecha_entrega: '2026-05-30',
    prioridad: 'baja',
    estado: 'finalizada',
    activo: true,
  },
  {
    id: 6,
    titulo: 'Monitoreo de Tráfico de Red SNMP',
    descripcion: 'Configurar agentes de escucha en routers virtuales para recopilar telemetría e incidencias de tráfico.',
    asignatura: 'Gestión de Redes',
    fecha_entrega: '2026-06-12',
    prioridad: 'media',
    estado: 'en proceso',
    activo: true,
  },
  {
    id: 7,
    titulo: 'Modelado de Rutas de Tráfico de Red Cifrado',
    descripcion: 'Analizar flujos de datos cifrados y esquemas de comportamiento para la detección temprana de ransomware.',
    asignatura: 'Seguridad de Redes',
    fecha_entrega: '2026-06-15',
    prioridad: 'alta',
    estado: 'pendiente',
    activo: true,
  }
];